<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container35axrbe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container35axrbe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container35axrbe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container35axrbe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container35axrbe\App_KernelDevDebugContainer([
    'container.build_hash' => '35axrbe',
    'container.build_id' => 'a4089d12',
    'container.build_time' => 1579550909,
], __DIR__.\DIRECTORY_SEPARATOR.'Container35axrbe');
